# Generated by Django 4.2.3 on 2023-07-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.FileField(default='', upload_to='cv/'),
        ),
    ]
