# Generated by Django 4.2.3 on 2023-07-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cv/'),
        ),
    ]
