# Generated by Django 4.2.3 on 2023-07-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact_alter_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(default='', upload_to='about'),
        ),
    ]
