# Generated by Django 4.2.3 on 2023-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_about_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nom_complet',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tellephone',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', max_length=500),
        ),
    ]
